apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
  namespace: rabbitmq
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: 63061/evdis-6277de022e37526dfdc2c20d567227d3@sha256:d256ecba3a86d61af8eb9a04d0a4f02631a03bafa241ad58bc0b0f6c8ee8b717
          args:
            - --delay=0
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "200m"
